name: Daily Journal Commit

on:
  schedule:
    - cron: "*/30 * * * *"   # Runs every 30 minutes
  workflow_dispatch:

permissions:
  contents: write   # ✅ allow pushing

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests library
        run: pip install requests

      - name: Run journal script
        run: python daily_journal.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto journal entry for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
