name: Daily Journal Automation

on:
  workflow_dispatch:   # 👈 Manual trigger option
  schedule:
    - cron: "0 9 * * *"   # Runs every day at 9 AM UTC

jobs:
  run-journal:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run journal script
        run: python journal.py

      - name: Commit and Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto journal entry for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push

